// Catalogo italiano della sezione Sicurezza del profilo (secondo fattore del Nazionale).
export const TESTI_SICUREZZA = {
  titolo: "Sicurezza dell’accesso",
  introduzione: "Dopo la password il sistema propone il metodo migliore tra quelli che hai attivato; al login puoi comunque sceglierne un altro.",
  proposto: (nome) => `Al login ti chiederemo: ${nome}.`,
  nessunMetodo: "Nessun metodo attivo: al prossimo accesso ti chiederemo di verificare l’email in anagrafica.",
  caricamento: "Caricamento dei metodi di accesso…",
  erroreStato: "Non è stato possibile leggere i metodi di accesso. Riprova.",
  riprova: "Riprova",
  metodi: { passkey: "passkey sul telefono", totp: "app di autenticazione", email: "codice via email" },
  password: "Password",
  annulla: "Annulla",
  continua: "Continua",
  inCorso: "Un momento…",
  email: {
    titolo: "Codice via email",
    descrizione: "Il metodo di base. Vale solo dopo la verifica dell’indirizzo in anagrafica.",
    verificata: (destinatario) => `Email verificata · ${destinatario}`,
    nonVerificata: "Email non ancora verificata: la verifichi al prossimo accesso con il codice che ti arriva.",
    assente: "Nessuna email valida in anagrafica: rivolgiti a un amministratore.",
  },
  authenticator: {
    titolo: "App di autenticazione",
    descrizione: "Google Authenticator, Microsoft Authenticator o simili: un codice a sei cifre che cambia ogni 30 secondi, anche senza rete.",
    nonAttivo: "Non attiva",
    attivaDal: (data) => `Attiva dal ${data}`,
    pendente: "Attivazione da completare",
    attiva: "Attiva",
    disattiva: "Disattiva",
    dialogoTitolo: "Attiva l’app di autenticazione",
    dialogoDescrizione: "Conferma la password: subito dopo compare il codice da inquadrare con l’app.",
    passoQr: "Apri l’app sul telefono, aggiungi un account e inquadra il codice. Se non riesci a scansionarlo, inserisci la chiave a mano. Poi scrivi qui il numero che l’app mostra.",
    qrAlt: "Codice QR da inquadrare con l’app di autenticazione",
    chiave: "Chiave da inserire a mano",
    codice: "Codice mostrato dall’app",
    conferma: "Conferma e attiva",
    disattivaTitolo: "Disattiva l’app di autenticazione",
    disattivaDescrizione: "Servono la password e un codice corrente dell’app. Dal prossimo accesso ti chiederemo il codice via email.",
    disattivaConferma: "Disattiva l’app",
    attivato: "App di autenticazione attiva. Dal prossimo accesso ti chiederemo il suo codice.",
    disattivato: "App di autenticazione disattivata.",
  },
  passkey: {
    titolo: "Passkey sul telefono",
    descrizione: "Una chiave che vive nel tuo telefono: al login inquadri un codice e confermi con impronta, volto o PIN. Niente da copiare.",
    nessuna: "Nessuna passkey registrata",
    aggiungi: "Aggiungi passkey",
    rimuovi: "Rimuovi",
    nonSupportata: "Questo browser non supporta le passkey.",
    dialogoTitolo: "Aggiungi una passkey",
    dialogoDescrizione: "Dai un nome alla passkey e conferma la password: subito dopo il browser ti chiede il telefono.",
    nome: "Nome della passkey",
    nomeSuggerito: "Il mio telefono",
    passoTelefono: "Il browser ti mostra un codice da inquadrare con il telefono, poi confermi con impronta, volto o PIN. Se Windows propone una chiave USB, premi Cambia e scegli il telefono. Servono Bluetooth acceso su entrambi e connessione a internet.",
    inAttesa: "In attesa del telefono…",
    riprova: "Riprova con il telefono",
    aggiunta: "Passkey aggiunta. Dal prossimo accesso ti proporremo il telefono.",
    rimozioneTitolo: "Rimuovi la passkey",
    rimozioneDescrizione: (nome) => `Conferma la password per rimuovere «${nome}». Se era l’unica, al login torneremo a proporti gli altri metodi.`,
    rimossa: "Passkey rimossa.",
    aggiuntaIl: (data) => `aggiunta il ${data}`,
    ultimoUso: (data) => `ultimo uso ${data}`,
    maiUsata: "mai usata",
    sincronizzata: "sincronizzata con l’account del telefono",
  },
};
